### ISSUE TITLE
Get tests running reliably against staging

### ISSUE THREAD

**Issue by peterjgilbert** [oasislabs/e2e-tests#55]
- [x] https://github.com/oasislabs/e2e-tests/issues/52
- [x] https://github.com/oasislabs/e2e-tests/issues/51
- [x] https://github.com/oasislabs/e2e-tests/issues/56
- [x] https://github.com/oasislabs/e2e-tests/issues/63
- [x] https://github.com/oasislabs/e2e-tests/issues/64
- [x] https://github.com/oasislabs/e2e-tests/issues/67
~- [ ] https://github.com/oasislabs/e2e-tests/issues/69~
- [ ] https://github.com/oasislabs/e2e-tests/issues/79
